-- kinglegacy.lua
return {
    {"ArcHub King Legacy", function() safeRun(function() loadstring(game:HttpGet("https://raw.githubusercontent.com/ChopLoris/ArcHub/main/main.lua"))() end) end},
    {"Tsuo Hub King Legacy", function() safeRun(function() loadstring(game:HttpGet("https://raw.githubusercontent.com/Tsuo7/TsuoHub/main/king%20legacy"))() end) end},
    {"Zee Hub King Legacy", function() safeRun(function() loadstring(game:HttpGet("https://zuwz.me/Ls-Zee-Hub-KL"))() end) end},
    {"Hyper Hub King Legacy", function() safeRun(function() loadstring(game:HttpGet("https://raw.githubusercontent.com/DookDekDEE/Hyper/main/script.lua"))() end) end},
    {"Vector Hub King Legacy", function() safeRun(function() loadstring(game:HttpGet("https://vectorhub.space"))() end) end},
    {"Wukong HUD King Legacy", function() safeRun(function() loadstring(game:HttpGet("https://raw.githubusercontent.com/duymanhm6-cyber/wukonghud/refs/heads/main/wukonghud"))() end) end},
    {"Fazium Hub King Legacy", function() safeRun(function() loadstring(game:HttpGet("https://raw.githubusercontent.com/ZaRdoOx/Fazium-files/main/Loader"))() end) end},
    {"Philippine Hub King Legacy", function() safeRun(function() loadstring(game:HttpGet("https://raw.githubusercontent.com/PrintH3lloW0rld/Philippine-hub/main/Philippine%20Hub%201.0"))() end) end},
    {"Hulk Hub King Legacy", function() safeRun(function() loadstring(game:HttpGet("https://raw.githubusercontent.com/HULKUexe/mobileX/main/FreeScript.lua"))() end) end},
    {"ShareHack King Legacy", function() safeRun(function() loadstring(game:HttpGet("https://raw.githubusercontent.com/SHAREHACK/script/main/kl"))() end) end},
    {"Zen Hub King Legacy", function() safeRun(function() loadstring(game:HttpGet("https://raw.githubusercontent.com/Zenhubtop/zen_hub_pr/main/zennewwwwui.lua"))() end) end},
    {"Strike Hub King Legacy", function() safeRun(function() loadstring(game:HttpGet("https://raw.githubusercontent.com/xDepressionx/Free-Script/main/AllScript.lua"))() end) end},
    {"SoggyWare King Legacy", function() safeRun(function() loadstring(game:HttpGet("https://raw.githubusercontent.com/SunkenMuch/Soggyware/main/Main"))() end) end},
    {"Scarface King Legacy", function() safeRun(function() loadstring(game:HttpGet("https://raw.githubusercontent.com/PainfulDestroyer/Roblox/main/King%20Legacy"))() end) end},
    {"Black GUI King Legacy", function() safeRun(function() loadstring(game:HttpGet("https://raw.githubusercontent.com/sannin9000/scripts/main/kinglegacy.lua"))() end) end},
    {"Auto Farm Level Hub", function() safeRun(function() loadstring(game:HttpGet("https://scriptpastebin.com/20k25"))() end) end},
    {"Auto Sea King Farm", function() safeRun(function() loadstring(game:HttpGet("https://raw.githubusercontent.com/ChopLoris/ArcHub/main/main.lua"))() end) end},
    {"Auto Ghost Ship Script", function() safeRun(function() loadstring(game:HttpGet("https://raw.githubusercontent.com/Tsuo7/TsuoHub/main/king%20legacy"))() end) end},
    {"Auto Dungeon Raid", function() safeRun(function() loadstring(game:HttpGet("https://zuwz.me/Ls-Zee-Hub-KL"))() end) end},
    {"Auto Boss Killer", function() safeRun(function() loadstring(game:HttpGet("https://raw.githubusercontent.com/DookDekDEE/Hyper/main/script.lua"))() end) end},
    {"Auto Fruits Collector", function() safeRun(function() loadstring(game:HttpGet("https://vectorhub.space"))() end) end},
    {"Auto Stats Maxer", function() safeRun(function() loadstring(game:HttpGet("https://raw.githubusercontent.com/duymanhm6-cyber/wukonghud/refs/heads/main/wukonghud"))() end) end},
    {"Auto Raid Farmer", function() safeRun(function() loadstring(game:HttpGet("https://raw.githubusercontent.com/ZaRdoOx/Fazium-files/main/Loader"))() end) end},
    {"Auto Quest Completer", function() safeRun(function() loadstring(game:HttpGet("https://raw.githubusercontent.com/PrintH3lloW0rld/Philippine-hub/main/Philippine%20Hub%201.0"))() end) end},
    {"Auto Hydra Hunter", function() safeRun(function() loadstring(game:HttpGet("https://raw.githubusercontent.com/HULKUexe/mobileX/main/FreeScript.lua"))() end) end},
    {"PVP Aimbot Script", function() safeRun(function() loadstring(game:HttpGet("https://raw.githubusercontent.com/SHAREHACK/script/main/kl"))() end) end},
    {"Silent Aim PVP", function() safeRun(function() loadstring(game:HttpGet("https://raw.githubusercontent.com/Zenhubtop/zen_hub_pr/main/zennewwwwui.lua"))() end) end},
    {"ESP Player Highlight", function() safeRun(function() loadstring(game:HttpGet("https://scriptpastebin.com/20k25"))() end) end},
    {"Infinite Jump Hack", function() safeRun(function() loadstring(game:HttpGet("https://raw.githubusercontent.com/xDepressionx/Free-Script/main/AllScript.lua"))() end) end},
    {"God Mode Script", function() safeRun(function() loadstring(game:HttpGet("https://raw.githubusercontent.com/SunkenMuch/Soggyware/main/Main"))() end) end},
    {"WalkSpeed Changer", function() safeRun(function() loadstring(game:HttpGet("https://raw.githubusercontent.com/PainfulDestroyer/Roblox/main/King%20Legacy"))() end) end},
    {"Fly Noclip Hack", function() safeRun(function() loadstring(game:HttpGet("https://raw.githubusercontent.com/sannin9000/scripts/main/kinglegacy.lua"))() end) end},
    {"Sea Event Auto Farm", function() safeRun(function() loadstring(game:HttpGet("https://raw.githubusercontent.com/ChopLoris/ArcHub/main/main.lua"))() end) end},
    {"Easter Egg Collector", function() safeRun(function() loadstring(game:HttpGet("https://raw.githubusercontent.com/Tsuo7/TsuoHub/main/king%20legacy"))() end) end},
    {"Beli Auto Farmer", function() safeRun(function() loadstring(game:HttpGet("https://zuwz.me/Ls-Zee-Hub-KL"))() end) end},
    {"Material Auto Farm", function() safeRun(function() loadstring(game:HttpGet("https://raw.githubusercontent.com/DookDekDEE/Hyper/main/script.lua"))() end) end},
    {"Fighting Style Buyer", function() safeRun(function() loadstring(game:HttpGet("https://vectorhub.space"))() end) end},
    {"Devil Fruit Sniper", function() safeRun(function() loadstring(game:HttpGet("https://raw.githubusercontent.com/duymanhm6-cyber/wukonghud/refs/heads/main/wukonghud"))() end) end},
    {"Kill Aura PVP", function() safeRun(function() loadstring(game:HttpGet("https://raw.githubusercontent.com/ZaRdoOx/Fazium-files/main/Loader"))() end) end},
    {"Bring Mob Script", function() safeRun(function() loadstring(game:HttpGet("https://raw.githubusercontent.com/PrintH3lloW0rld/Philippine-hub/main/Philippine%20Hub%201.0"))() end) end},
    {"Auto Skill Spammer", function() safeRun(function() loadstring(game:HttpGet("https://raw.githubusercontent.com/HULKUexe/mobileX/main/FreeScript.lua"))() end) end},
    {"Teleport Hub", function() safeRun(function() loadstring(game:HttpGet("https://raw.githubusercontent.com/SHAREHACK/script/main/kl"))() end) end},
    {"Anti Lag Optimizer", function() safeRun(function() loadstring(game:HttpGet("https://raw.githubusercontent.com/Zenhubtop/zen_hub_pr/main/zennewwwwui.lua"))() end) end},
    {"One Shot Script", function() safeRun(function() loadstring(game:HttpGet("https://scriptpastebin.com/20k25"))() end) end},
    {"Auto Level 4400", function() safeRun(function() loadstring(game:HttpGet("https://raw.githubusercontent.com/xDepressionx/Free-Script/main/AllScript.lua"))() end) end},
    {"Sea Beast Race Auto", function() safeRun(function() loadstring(game:HttpGet("https://raw.githubusercontent.com/SunkenMuch/Soggyware/main/Main"))() end) end},
    {"Dungeon Auto Clear", function() safeRun(function() loadstring(game:HttpGet("https://raw.githubusercontent.com/PainfulDestroyer/Roblox/main/King%20Legacy"))() end) end},
    {"Mukuro Hub King Legacy", function() safeRun(function() loadstring(game:HttpGet("https://raw.githubusercontent.com/sannin9000/scripts/main/kinglegacy.lua"))() end) end},
    {"Xenon Hub King Legacy", function() safeRun(function() loadstring(game:HttpGet("https://raw.githubusercontent.com/ChopLoris/ArcHub/main/main.lua"))() end) end},
    {"One X Hub King Legacy", function() safeRun(function() loadstring(game:HttpGet("https://raw.githubusercontent.com/Tsuo7/TsuoHub/main/king%20legacy"))() end) end},
    {"TVF Hub King Legacy", function() safeRun(function() loadstring(game:HttpGet("https://raw.githubusercontent.com/LHking123456/TVFRPp5brCJ2Z/refs/heads/main/Legacy"))() end) end},
    {"LOL Hub King Legacy", function() safeRun(function() loadstring(game:HttpGet("https://raw.githubusercontent.com/LOLking123456/king/main/legacy"))() end) end},
    {"Egg Farm Script", function() safeRun(function() loadstring(game:HttpGet("https://raw.githubusercontent.com/zearx/r-g/refs/heads/main/kl/egg.lua"))() end) end},
    {"Instant Raid Script", function() safeRun(function() loadstring(game:HttpGet("https://raw.githubusercontent.com/DookDekDEE/Hyper/main/script.lua"))() end) end},
    {"Infinite Stats Hack", function() safeRun(function() loadstring(game:HttpGet("https://raw.githubusercontent.com/duymanhm6-cyber/wukonghud/refs/heads/main/wukonghud"))() end) end},
    {"Speed Hack King Legacy", function() safeRun(function() loadstring(game:HttpGet("https://vectorhub.space"))() end) end},
    {"Noclip Fly Script", function() safeRun(function() loadstring(game:HttpGet("https://raw.githubusercontent.com/ZaRdoOx/Fazium-files/main/Loader"))() end) end},
    {"Boss Auto Killer", function() safeRun(function() loadstring(game:HttpGet("https://raw.githubusercontent.com/PrintH3lloW0rld/Philippine-hub/main/Philippine%20Hub%201.0"))() end) end},
    {"Sea King Hunter", function() safeRun(function() loadstring(game:HttpGet("https://raw.githubusercontent.com/HULKUexe/mobileX/main/FreeScript.lua"))() end) end},
    {"Hydra Auto Farm", function() safeRun(function() loadstring(game:HttpGet("https://raw.githubusercontent.com/SHAREHACK/script/main/kl"))() end) end},
    {"Ghost Ship Farmer", function() safeRun(function() loadstring(game:HttpGet("https://raw.githubusercontent.com/Zenhubtop/zen_hub_pr/main/zennewwwwui.lua"))() end) end},
    {"Fruit Auto Snipe", function() safeRun(function() loadstring(game:HttpGet("https://scriptpastebin.com/20k25"))() end) end},
    {"PVP God Mode", function() safeRun(function() loadstring(game:HttpGet("https://raw.githubusercontent.com/xDepressionx/Free-Script/main/AllScript.lua"))() end) end},
    {"Auto Buy All", function() safeRun(function() loadstring(game:HttpGet("https://raw.githubusercontent.com/SunkenMuch/Soggyware/main/Main"))() end) end},
    {"Leveling Script", function() safeRun(function() loadstring(game:HttpGet("https://raw.githubusercontent.com/PainfulDestroyer/Roblox/main/King%20Legacy"))() end) end},
    {"Beli Maximizer", function() safeRun(function() loadstring(game:HttpGet("https://raw.githubusercontent.com/sannin9000/scripts/main/kinglegacy.lua"))() end) end},
    {"Event Farm Script", function() safeRun(function() loadstring(game:HttpGet("https://raw.githubusercontent.com/ChopLoris/ArcHub/main/main.lua"))() end) end},
    {"Mobile Optimized Hub", function() safeRun(function() loadstring(game:HttpGet("https://raw.githubusercontent.com/HULKUexe/mobileX/main/FreeScript.lua"))() end) end},
    {"PC Ultimate Hub", function() safeRun(function() loadstring(game:HttpGet("https://raw.githubusercontent.com/Tsuo7/TsuoHub/main/king%20legacy"))() end) end},
    {"Keyless Auto Farm", function() safeRun(function() loadstring(game:HttpGet("https://zuwz.me/Ls-Zee-Hub-KL"))() end) end},
    {"Update 10 Script", function() safeRun(function() loadstring(game:HttpGet("https://raw.githubusercontent.com/DookDekDEE/Hyper/main/script.lua"))() end) end},
    {"Easter Event Hub", function() safeRun(function() loadstring(game:HttpGet("https://vectorhub.space"))() end) end},
    {"Sea Beast Auto", function() safeRun(function() loadstring(game:HttpGet("https://raw.githubusercontent.com/duymanhm6-cyber/wukonghud/refs/heads/main/wukonghud"))() end) end},
    {"Raid Instant Clear", function() safeRun(function() loadstring(game:HttpGet("https://raw.githubusercontent.com/ZaRdoOx/Fazium-files/main/Loader"))() end) end},
    {"Stats Auto Add", function() safeRun(function() loadstring(game:HttpGet("https://raw.githubusercontent.com/PrintH3lloW0rld/Philippine-hub/main/Philippine%20Hub%201.0"))() end) end},
    {"Boss Rush Script", function() safeRun(function() loadstring(game:HttpGet("https://raw.githubusercontent.com/HULKUexe/mobileX/main/FreeScript.lua"))() end) end},
    {"PVP Silent Aim", function() safeRun(function() loadstring(game:HttpGet("https://raw.githubusercontent.com/SHAREHACK/script/main/kl"))() end) end},
    {"Highlight ESP", function() safeRun(function() loadstring(game:HttpGet("https://raw.githubusercontent.com/Zenhubtop/zen_hub_pr/main/zennewwwwui.lua"))() end) end},
    {"Fast Travel Hub", function() safeRun(function() loadstring(game:HttpGet("https://scriptpastebin.com/20k25"))() end) end},
    {"Infinite Yield Style", function() safeRun(function() loadstring(game:HttpGet("https://raw.githubusercontent.com/xDepressionx/Free-Script/main/AllScript.lua"))() end) end},
    {"Advanced Farm Hub", function() safeRun(function() loadstring(game:HttpGet("https://raw.githubusercontent.com/SunkenMuch/Soggyware/main/Main"))() end) end},
    {"Pro Player Script", function() safeRun(function() loadstring(game:HttpGet("https://raw.githubusercontent.com/PainfulDestroyer/Roblox/main/King%20Legacy"))() end) end},
    {"Max Stats Loader", function() safeRun(function() loadstring(game:HttpGet("https://raw.githubusercontent.com/sannin9000/scripts/main/kinglegacy.lua"))() end) end},
    {"Full Auto Hub", function() safeRun(function() loadstring(game:HttpGet("https://raw.githubusercontent.com/ChopLoris/ArcHub/main/main.lua"))() end) end},
    {"Legacy Dominator", function() safeRun(function() loadstring(game:HttpGet("https://raw.githubusercontent.com/Tsuo7/TsuoHub/main/king%20legacy"))() end) end},
    {"Ultimate King Script", function() safeRun(function() loadstring(game:HttpGet("https://zuwz.me/Ls-Zee-Hub-KL"))() end) end},
    {"King Legacy Master", function() safeRun(function() loadstring(game:HttpGet("https://raw.githubusercontent.com/DookDekDEE/Hyper/main/script.lua"))() end) end},
    {"OP Farm Script", function() safeRun(function() loadstring(game:HttpGet("https://vectorhub.space"))() end) end},
    {"No Key Hub", function() safeRun(function() loadstring(game:HttpGet("https://raw.githubusercontent.com/duymanhm6-cyber/wukonghud/refs/heads/main/wukonghud"))() end) end},
    {"2026 Update Hub", function() safeRun(function() loadstring(game:HttpGet("https://raw.githubusercontent.com/ZaRdoOx/Fazium-files/main/Loader"))() end) end},
    {"Mobile King Legacy", function() safeRun(function() loadstring(game:HttpGet("https://raw.githubusercontent.com/HULKUexe/mobileX/main/FreeScript.lua"))() end) end},
    {"PC King Legacy", function() safeRun(function() loadstring(game:HttpGet("https://raw.githubusercontent.com/SHAREHACK/script/main/kl"))() end) end},
    {"Best King Hub", function() safeRun(function() loadstring(game:HttpGet("https://raw.githubusercontent.com/Zenhubtop/zen_hub_pr/main/zennewwwwui.lua"))() end) end},
    {"Fast Level Script", function() safeRun(function() loadstring(game:HttpGet("https://scriptpastebin.com/20k25"))() end) end},
    {"Auto Everything", function() safeRun(function() loadstring(game:HttpGet("https://raw.githubusercontent.com/xDepressionx/Free-Script/main/AllScript.lua"))() end) end},
    {"King Legacy Pro", function() safeRun(function() loadstring(game:HttpGet("https://raw.githubusercontent.com/SunkenMuch/Soggyware/main/Main"))() end) end},
    {"Legacy Auto Player", function() safeRun(function() loadstring(game:HttpGet("https://raw.githubusercontent.com/PainfulDestroyer/Roblox/main/King%20Legacy"))() end) end},
    {"God Tier Script", function() safeRun(function() loadstring(game:HttpGet("https://raw.githubusercontent.com/sannin9000/scripts/main/kinglegacy.lua"))() end) end}
}
